Repository italia/eid-wallet-it-docs, pull requests merged in 2024-06, with the labels that each got.

#301 Wallet Attestation new requirement
  docs/en/wallet-attestation.rst
Labels: 1-approval-required

#328 Entity Configurations and Metadata for PID/(Q)EAA Providers and RPs
  docs/common/common_definitions.rst
  docs/en/conf.py
  docs/en/index.rst
  docs/en/pid-eaa-entity-configuration.rst
  docs/en/pid-eaa-issuance.rst
  docs/en/relying-party-entity-configuration.rst
  docs/en/relying-party-solution.rst
  docs/en/remote-flow.rst
  docs/en/trust.rst
  docs/en/wallet-solution.rst
  examples/ec-eaa.json
  examples/ec-rp.json
  examples/presentation-definition.json
Labels: issuance, presentation, trust-model

#307 Update credential revocation reason from issuer's perspective
  docs/en/revocation-lists.rst
Labels: 1-approval-required

#335 Fixed colon in the text
  docs/en/pid-eaa-issuance.rst
  docs/en/wallet-attestation.rst
Labels: editorial, 1-approval-required

#330 [PID/(Q)EAA - SD-JWT parameters ] trust chain
  docs/en/trust.rst
Labels: 1-approval-required

#339 Non-normative examples in the Issuance
  docs/en/pid-eaa-issuance.rst
  examples/at-dpop-header.json
  examples/at-dpop-payload.json
  examples/credential-error.json
  examples/credential-jwt-proof-header.json
  examples/credential-jwt-proof-payload.json
  examples/credential-request.json
  examples/credential-response.json
  examples/par-error.json
  examples/par-response.json
  examples/request-object-header.json
  examples/request-object-payload.json
  examples/token-error.json
  examples/token-response.json
  examples/wa-pop-header.json
  examples/wa-pop-payload.json
Labels: issuance, editorial
