Repository italia/eid-wallet-it-docs, pull requests merged in 2025-01, with the labels that each got.

#511 Alignments of Data Model Section with SD-JWT and SD-JWT-VC latest drafts
  docs/common/common_definitions.rst
  docs/en/pid-eaa-data-model.rst
  docs/en/pid-eaa-entity-configuration.rst
  docs/en/pid-eaa-issuance.rst
  docs/en/relying-party-entity-configuration.rst
  docs/en/remote-flow.rst
  docs/en/ssi-introduction.rst
  docs/en/trust.rst
  docs/en/wallet-attestation.rst
  examples/credential-request.json
  examples/ec-eaa.json
  examples/ec-rp.json
  examples/pid-json-example-payload.json
  examples/pid-mdoc-cbor-example.txt
  examples/pid-sd-jwt-example-header.json
  examples/pid-sd-jwt-example-payload.json
  examples/presentation-definition.json
  examples/qeaa-json-example-payload.json
  examples/qeaa-sd-jwt-example-header.json
  examples/qeaa-sd-jwt-example-payload.json
  examples/vc-metadata-type.json
Labels: specification alignment

#517 Backup and Restore
  docs/common/standards.rst
  docs/en/backup-restore.rst
  images/Backup_flow.svg
  images/Restore_Flow.svg
Labels: wallet-solution

#507 Alignments with OpenID4VP Draft 22
  docs/common/common_definitions.rst
  docs/common/standards.rst
  docs/en/pid-eaa-entity-configuration.rst
  docs/en/pid-eaa-issuance.rst
  docs/en/relying-party-entity-configuration.rst
  docs/en/remote-flow.rst
  docs/en/security-privacy-considerations.rst
  docs/en/trust.rst
  docs/en/wallet-attestation.rst
  examples/ec-eaa.json
  examples/ec-rp.json
Labels: presentation, specification alignment

#530 Universal Links vs Custom URL Schemes Support
  docs/common/standards.rst
  docs/en/remote-flow.rst
  docs/en/wallet-attestation.rst
Labels: wallet-solution, presentation, 1-approval-required

#533 Alignments with Draft 15 OpenID4VCI and Issuance Error Management
  docs/common/common_definitions.rst
  docs/common/standards.rst
  docs/en/pid-eaa-entity-configuration.rst
  docs/en/pid-eaa-issuance.rst
  examples/credential-request.json
  examples/credential-response-deferred.json
  examples/credential-response.json
  examples/ec-eaa.json
  examples/nonce-response.json
  examples/notification-error.json
  examples/token-response.json
  images/Low-Level-Flow-ITWallet-PID-QEAA-Issuance.svg
Labels: issuance

#529 Alignment of PID Data Model with IA
  docs/common/common_definitions.rst
  docs/en/defined-terms.rst
  docs/en/pid-eaa-data-model.rst
  docs/en/pid-eaa-entity-configuration.rst
  examples/ec-eaa.json
  examples/pid-json-example-payload.json
  examples/pid-mdoc-cbor-example.txt
  examples/pid-sd-jwt-example-payload.json
  examples/qeaa-json-example-payload.json
  examples/qeaa-sd-jwt-example-payload.json
  examples/vc-metadata-type.json
Labels: 1-approval-required
